### PR TITLE
Milestone 1 candidate

### PR DESCRIPTION
**Pull request by GeorgeJJW**
Breaking changes:

- Renamed repo to something more meaningful. Note that this might break your old forks, you might have to refork the master repo after the merge of this PR.

- Renamed CONTRIBUTING.md, CONDUCT.md, and LICENSE.md as per the milestone 1 requirements.

- Renamed proposal.md, and moved the file under `/doc`.

Changes:

- Edited question of interest section, added some study background and motivation, added questions for measuring competitiveness, some minor reformatting.

- Added potential confounds section and rationale.

- Edited plan of analysis section, converted some point forms to full sentences, as per the writing requirements of milestone 1, some minor reformatting.

- Some minor editing on the ethics section.

- Added references section.

- Minor fix in the CONTRIBUTING.md of some links and images.

- Updated README.md to include link to the proposal.

### CODE REVIEW

**Comment by sedv8808** [comment]
Hi @GeorgeJJW 

I have read through the `Proposal` and I think it looks amazing. Thank you so much for doing all the research in psychology and going further in the nitty gritty details for this survey. I appreciate it. 

I am just spotting a Grammar mistake in the Main Question of interest. I think it should be: `Does self-reported competitiveness influence where an individual prefers to sit in class?`

Other than that, I find this awesome.

**Comment by GeorgeJJW** [comment]
You are right! Nice catch, fixed with 77b5da2b4fb909fac647d7b445f840eb91d51446.

**Comment by GeorgeJJW** [comment]
You are right! Nice catch, fixed with 77b5da2b4fb909fac647d7b445f840eb91d51446 and 328079efe335ef47ab0760b53747ed3cf10285f7 .

**Comment by aylapear** [comment]
Looks great to me too. Thanks for putting it all together George it read smoothly. Good catch with the contributing doc repo names, I noticed that last night and planned to fix it today.

**Review by aylapear — COMMENTED** [review]
Everything looks great! Approved

**Review by aylapear — APPROVED** [review]

**Review by zxzzhangg — APPROVED** [review]
Everything looks good on me. Thanks for the work.

**Comment by GeorgeJJW** [comment]
Closed.

**Pull request merged**
