### PR TITLE
add analysis of model 2

### PR DESCRIPTION
**Pull request by zxzzhangg**
Hi, I have added the analysis of model2 in the report.Rmd. Please take a look and let me know anything to modify or correct. Thanks.

### CODE REVIEW

**Review by aylapear — COMMENTED** [review]
Is there a way to generate the table from code instead of manually creating with markdown formatting?

**Comment by zxzzhangg** [comment]
> Is there a way to generate the table from code instead of manually creating with markdown formatting?

This is not manually creating the markdown formatting, I use this line of code `kable(tableit,format='markdown')` where tableit is my summary data frame that is manually created.

**Review by GeorgeJJW — COMMENTED** [review]
Do you mind solving this merge conflict real quick, I just merged @sedv8808's #20, you just need to do a git pull and solve some conflicts on the final_report.Rmd, and do another commit.

**Review by GeorgeJJW — APPROVED** [review]
Nice fix. Merging it so we can all see the rendered plots.

**Comment by sedv8808** [comment]
Woot, this is looking great!

**Pull request merged**
